import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { DollarSign, Coins, Bot } from "lucide-react";

export function KPICards() {
  return (
    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
      {/* Total Value Locked */}
      <Card className="bg-card border-border rounded-sm">
        <CardHeader className="flex flex-row items-center justify-between pb-2">
          <CardTitle className="text-sm font-medium text-muted-foreground">
            Total Value Locked
          </CardTitle>
          <DollarSign className="h-4 w-4 text-muted-foreground" />
        </CardHeader>
        <CardContent>
          <div className="text-3xl font-bold font-mono text-foreground">$12,405.00</div>
          <p className="text-xs text-accent mt-1">
            +12% vs last epoch
          </p>
        </CardContent>
      </Card>

      {/* 24h Yield */}
      <Card className="bg-card border-border rounded-sm">
        <CardHeader className="flex flex-row items-center justify-between pb-2">
          <CardTitle className="text-sm font-medium text-muted-foreground">
            24h Yield
          </CardTitle>
          <Coins className="h-4 w-4 text-primary" />
        </CardHeader>
        <CardContent>
          <div className="text-3xl font-bold font-mono text-primary">345 QIE</div>
          <p className="text-xs text-muted-foreground mt-1">
            Generated by AI trading
          </p>
        </CardContent>
      </Card>

      {/* Active Agents */}
      <Card className="bg-card border-border rounded-sm">
        <CardHeader className="flex flex-row items-center justify-between pb-2">
          <CardTitle className="text-sm font-medium text-muted-foreground">
            Active Agents
          </CardTitle>
          <Bot className="h-4 w-4 text-accent" />
        </CardHeader>
        <CardContent>
          <div className="flex items-center gap-3">
            <span className="text-3xl font-bold font-mono text-foreground">3 / 5</span>
          </div>
          <div className="flex items-center gap-2 mt-1">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-accent opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-accent"></span>
            </span>
            <span className="text-xs text-accent">OPERATIONAL</span>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
